LibraryManagementSystem/LMSsite/LMSapp/urls.py
from django.contrib import admin
from django.urls import path, include
from LMSapp import views

app_name = 'LMSapp'
urlpatterns = [
    path('', views.index, name='index'),
    path('addbook', views.addBook, name='addbook'),
    path('addmember', views.addMember, name='addmember'),
    path('viewbook', views.viewBooks, name='viewbook'),
    path('viewmembers', views.viewMembers, name='viewmembers'),
    path('updatebook/<int:book_id>', views.updateBook, name='updatebook'),
    path('returnbook', views.bookReturn, name='returnbook'),
    path('return/<int:book_id>', views.returnSucc, name='returnsuc'),
    path('updatemember/<int:member_id>',
         views.updateMember, name='updatemember'),
    path('deregistermember/<int:member_id>',
         views.deleteMemeber, name='deletemember'),
    path('deletebook/<int:book_id>', views.deleteBook, name='deletebook'),
]

LibraryManagementSystem/LMSsite/LMSsite/urls.py
from django.contrib import admin
from django.urls import path, include
from LMSapp import urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('LMSapp.urls')),
]

LibraryManagementSystem/LMSsite/LMSapp/models.py
from django.db import models

# Create your models here.


class Students(models.Model):

    def __str__(self):
        return self.studentName

    studentID = models.IntegerField(primary_key=True)
    studentName = models.CharField(max_length=100)
    studentEmailID = models.CharField(max_length=100)


class Books(models.Model):

    def __str__(self):
        return self.bookname

    bookID = models.IntegerField(primary_key=True)
    bookname = models.CharField(max_length=100)
    bookPrice = models.FloatField()
    bookState = models.CharField(max_length=100)


class BoorowedBooks(models.Model):

    def __str__(self):
        return str(self.borrowID)

    borrowID = models.IntegerField(primary_key=True)
    stduent = models.ForeignKey(Students, on_delete=models.CASCADE)
    book = models.ForeignKey(Books, on_delete=models.CASCADE)

LibraryManagementSystem/LMSsite/LMSapp/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .models import Books, Students, BoorowedBooks
# Create your views here.


def index(request):
    allBooks = Books.objects.all()
    allStudents = Students.objects.all()
    if request.method == 'POST':
        studentemailid_f = request.POST.get('studentEmailID')
        # print(request.POST.get('studentEmailID'))
        try:
            studentExists = Students.objects.get(
                studentEmailID=studentemailid_f)
            # print(studentExists.studentName)
        except:
            studentExists = None
        if studentExists is not None:
            bookid_f = request.POST.get('bookID')
            # print(request.POST.get('bookID'))
            try:
                isBookAvailable = Books.objects.get(bookID=bookid_f)
                # print(isBookAvailable.bookname)
            except:
                isBookAvailable = None
            if isBookAvailable is not None:
                if isBookAvailable.bookState == "available":
                    boorowedBook = BoorowedBooks(
                        stduent=studentExists, book=isBookAvailable)
                    boorowedBook.save()
                    isBookAvailable.bookState = "notavailable"
                    isBookAvailable.save()
                    context = {
                        'books': allBooks,
                        'students': allStudents,
                        'flag': True,
                        'msg': 'Book is assigned successfully to {}'.format(studentExists.studentName)
                    }
                    return render(request, 'LMSapp/index.html', context=context)
                else:
                    context = {
                        'books': allBooks,
                        'students': allStudents,
                        'flag': True,
                        'msg': 'Book is already assigned'
                    }
                    return render(request, 'LMSapp/index.html', context=context)
            else:
                context = {
                    'books': allBooks,
                    'students': allStudents,
                    'flag': True,
                    'msg': 'Book is not available'
                }
                return render(request, 'LMSapp/index.html', context=context)
        else:
            context = {
                'books': allBooks,
                'students': allStudents,
                'flag': True,
                'msg': 'Verify student mail id'
            }
            return render(request, 'LMSapp/index.html', context=context)
    context = {
        'books': allBooks,
        'students': allStudents,
        'flag': False,
        'msg': ''
    }

    return render(request, 'LMSapp/index.html', context=context)


def addBook(request):
    if request.method == 'POST':
        bookName = request.POST.get('bookname')
        bookPrice = request.POST.get('bookPrice')
        bookState = request.POST.get('bookState')
        book = Books(bookname=bookName, bookPrice=bookPrice,
                     bookState=bookState)
        book.save()
        context = {'flag': True}
        return render(request, 'LMSapp/addbook.html', context=context)
    context = {'flag': False}
    return render(request, 'LMSapp/addbook.html', context=context)


def addMember(request):
    if request.method == 'POST':
        studentName = request.POST.get('studentName')
        studentEmailID_new = request.POST.get('studentEmailID')
        try:
            studentExist = Students.objects.get(
                studentEmailID=studentEmailID_new)
        except:
            studentExist = None
        if studentExist is not None:
            context = {'flag': True, 'msg': "Student is already registered"}
            return render(request, 'LMSapp/addMember.html', context=context)
        else:
            student = Students(studentName=studentName,
                               studentEmailID=studentEmailID_new)
            student.save()
            context = {'flag': True, 'msg': "Student registered succesfully"}
            return render(request, 'LMSapp/addMember.html', context=context)
    context = {'flag': False, 'msg': "First Time"}
    return render(request, 'LMSapp/addMember.html', context=context)


def viewBooks(request):
    try:
        allBooks = Books.objects.all()
    except:
        allBooks = None
    if allBooks is not None:
        for book in allBooks:
            print(book.bookname)
        context = {'flag': False, 'msg': "", 'data': allBooks}
        return render(request, 'LMSapp/viewbooks.html', context=context)
    else:
        context = {'flag': False, 'msg': "No books found", 'data': allBooks}
        return render(request, 'LMSapp/viewbooks.html', context=context)


def viewMembers(request):

    try:
        allMembers = Students.objects.all()
    except:
        allMembers = None
    if allMembers is not None:
        context = {'flag': False, 'msg': '', 'data': allMembers}
        return render(request, 'LMSapp/viewmembers.html', context=context)
    else:
        context = {'flag': False,
                   'msg': 'No Members are registered here', 'data': allMembers}
        return render(request, 'LMSapp/viewmembers.html', context=context)


def updateBook(request, book_id):
    if request.method == 'POST':
        bookname_f = request.POST.get('bookname')
        bookPrice_f = request.POST.get('bookPrice')
        book = Books.objects.get(bookID=request.POST.get('bookID'))
        oldbookname = book.bookname
        oldbookprice = book.bookPrice
        oldbookState = book.bookState
        if bookname_f == '':
            book.bookname = oldbookname
        else:
            book.bookname = bookname_f
        if bookPrice_f == '':
            book.bookPrice = oldbookprice
        else:
            book.bookPrice = bookPrice_f
        book.save()
        return redirect('/viewbook')

    book = Books.objects.get(bookID=book_id)
    if book.bookState == 'available':
        bookSelected = True
    else:
        bookSelected = False
    context = {
        'book': book,
        'bookSelected': bookSelected
    }
    return render(request, 'LMSapp/updatebook.html', context=context)


def bookReturn(request):
    if request.method == 'POST':
        studentemailid_f = request.POST.get('studentEmailID')
        try:
            studentExists = Students.objects.get(studentEmailID=studentEmailID)
        except:
            studentExists = False

        if studentExists is not None:
            borrowedBooks = []
            allBorrowedBooks = BoorowedBooks.objects.all()
            for book in allBorrowedBooks:
                if book.stduent.studentEmailID == studentemailid_f:
                    borrowedBooks.append(book.book)
            if len(borrowedBooks) > 0:
                context = {
                    'flag': True,
                    'borrowedBooks': borrowedBooks,
                    'Bookflag': True,
                    'studentExist': True,
                    'msg': ""
                }
                return render(request, 'LMSapp/returnbook.html', context=context)
            else:
                context = {
                    'flag': True,
                    'borrowedBooks': borrowedBooks,
                    'Bookflag': False,
                    'studentExist': True,
                    'msg': " Student has not borrowed any books from libabry"
                }
                return render(request, 'LMSapp/returnbook.html', context=context)
        else:
            context = {
                'flag': True,
                'borrowedBooks': [],
                'Bookflag': False,
                'NoBookFlag': False,
                'studentExist': False,
                'msg': " Student does exists"
            }
            return render(request, 'LMSapp/returnbook.html', context=context)

    context = {
        'flag': False,
        'borrowedBooks': [],
        'Bookflag': False,
        'studentExist': False,
        'msg': ""

    }
    return render(request, 'LMSapp/returnbook.html', context=context)


def returnSucc(request, book_id):
    try:
        print(book_id)
        bookBorrowed = Books.objects.get(bookID=book_id)
        print("From Book Model ")
        print(bookBorrowed.bookID)
        print(bookBorrowed.bookState)
        bookBorrowed.bookState = 'available'
        bookBorrowed.save()
        borrowedBooks = BoorowedBooks.objects.all()
        for book in borrowedBooks:
            print(book.book.bookID)
            if book.book.bookID == bookBorrowed.bookID:
                book.delete()
    except:
        borrowedBooks = None
        return HttpResponse("Something went wrong")

    return redirect('/returnbook')


def updateMember(request, member_id):
    if request.method == 'POST':
        studentName_f = request.POST.get('studentName')
        studentEmailID_f = request.POST.get('studentEmailID')
        student = Students.objects.get(studentID=member_id)
        oldstudentName = student.studentName
        oldstudentEmailID = student.studentEmailID
        if studentName_f == '':
            student.studentName = oldstudentName
        else:
            student.studentName = studentName_f
        if studentEmailID_f == '':
            student.studentEmailID = oldstudentEmailID
        else:
            student.studentEmailID = studentEmailID_f
        student.save()
        return redirect('/viewmembers')

    member = Students.objects.get(studentID=member_id)
    if member is not None:
        context = {
            'student': member
        }
        return render(request, 'LMSapp/updateMember.html', context=context)
    else:
        return redirect('/viewmembers')


def deleteMemeber(request, member_id):
    try:
        print("*******************************")
        member = Students.objects.get(studentID=member_id)
        allBorrowedBooks = BoorowedBooks.objects.all()
        BorrowedBooks = []

LibraryManagementSystem/LMSsite/LMSapp/templates/LMSapp/addMember.html
{% extends 'LMSapp/base.html' %}
{% block body %}
<div class="container mt-6">
    <div class="row">
        <div class="col-md-6">
            <form method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="form-group">
                    <label for="bookname">Student Name</label>
                    <input type="text" class="form-control" name="studentName" id="studentName" placeholder="Name">
                </div>
                <div class="form-group">
                    <label for="bookPrice">Student emailID</label>
                    <input type="email" class="form-control" id="studentEmailID" name="studentEmailID">
                </div>
                <button type="submit" class="btn btn-primary">Submit</button>
            </form>
        </div>
    </div>
    {% if flag %}
    <div class="row">
        <div class="col-md-4">
           <p> {{ msg }} </p> 
        </div>
    </div>
    {% endif %}
</div>
{% endblock %}

LibraryManagementSystem/LMSsite/LMSapp/templates/LMSapp/addbook.html
{% extends 'LMSapp/base.html' %}
{% block body %}

<div class="container mt-6">
    <div class="row">
        <div class="col-md-6">
            <form method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="form-group">
                    <label for="bookname">Book Name</label>
                    <input type="text" class="form-control" name="bookname" id="bookname" placeholder="Name">
                </div>
                <div class="form-group">
                    <label for="bookPrice">Book Price</label>
                    <input type="text" class="form-control" id="bookPrice" name="bookPrice">
                </div>
                <div class="form-group">
                    <label for="bookState">Book State</label>
                    <select class="form-control" name="bookState" id="bookState">
                        <option value="available">Availabel</option>
                        <option value="notavailable">Not available</option>
                    </select>
                </div>
                <button type="submit" class="btn btn-primary">Submit</button>
            </form>
        </div>
    </div>
    {% if flag %}
    <div class="row">
        <div class="col-md-4">
            <p>Book added succesfully</p>
        </div>
    </div>
    {% endif %}
</div>

{% endblock %}

LibraryManagementSystem/LMSsite/LMSapp/templates/LMSapp/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>LMS APP</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
        integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'LMSapp/style.css' %}">
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand navbar-brand-mod" href="{% url 'LMSapp:index' %}">LMS</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'LMSapp:index' %}">Assign Book <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'LMSapp:addbook' %}">Add Book</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'LMSapp:addmember' %}">Add Member</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'LMSapp:viewbook' %}">View Books</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'LMSapp:viewmembers' %}">View Members</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'LMSapp:returnbook' %}">Return Book</a>
                </li>
            </ul>
        </div>
    </nav>
    {% block body %}
    {% endblock %}
</body>

</html>

LibraryManagementSystem/LMSsite/LMSapp/templates/LMSapp/index.html
{% extends 'LMSapp/base.html' %}
{% block body %}
    
<div class="container mt-6">
    <div class="row">
        <div class="col-md-6">
            <form method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="form-group">
                    <label for="studentEmailID">Stduent email id</label>
                    <input type="text" class="form-control" name="studentEmailID" id="studentEmailID" placeholder="email ID">                    
                </div>
                <div class="form-group">
                    <label for="bookState">Book Name</label>
                    <select class="form-control" name="bookID" id="bookID">
                        {% for book in books %}
                        <option value="{{book.bookID}}">{{book.bookname}}</option>
                        {% endfor %}
                    </select>
                    
                </div>
                <button type="submit" class="btn btn-primary">Submit</button>
            </form>
        </div>
    </div>
    {% if flag %}
    <div class="row">
        <div class="col-md-4">
           <p>{{msg}}</p> 
        </div>
    </div>
    {% endif %}
</div>

{% endblock %}

LibraryManagementSystem/LMSsite/LMSapp/templates/LMSapp/returnbook.html
{% extends 'LMSapp/base.html' %}
{% block body %}
<div class="container mt-6">
    <div class="row">
        <div class="col-md-6">
            <form method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                <input type="hidden" name="bookID" value={{book.bookID}}>
                <div class="form-group">
                    <label for="bookname">Student Email ID</label>
                    <input type="email" class="form-control" name="studentEmailID" id="studentEmailID"
                        placeholder="Enter email ID of  student">
                </div>
                <button type="submit" class="btn btn-primary">Submit</button>
            </form>
        </div>
    </div>
    <div class="container">
        {% if flag %}
            {%if studentExist%}
                {% if Bookflag %}
                    <div class="row">
                    {% for book in borrowedBooks %}
                        <div class="col-md-4">
                            <div class="card-body">
                                <h3 class="card-title">{{book.bookname}}</h3>
                                <h6 class="card-subtitle mb-2 text-muted">{{book.bookPrice}}</h6>
                                <p class="card-text">{{book.bookState}}</p>
                                <a href="{% url 'LMSapp:returnsuc' book.bookID %}" class="card-link">Return</a>
                            </div>
                        </div>
                    {% endfor %}
                    </div>
                {% else %}
                    <div class="row">
                        <div class="col-md-4">
                            {{msg}}
                        </div>
                    </div>
                {% endif %}
            {% else %}
        <div class="row">
            <div class="col-md-4">
                <p>
                    {{msg}}
                </p>
            </div>
        </div>
            {% endif %}
        {% endif %}
    </div>
</div>
{% endblock %}

LibraryManagementSystem/LMSsite/LMSapp/templates/LMSapp/updatebook.html
{% extends 'LMSapp/base.html' %}
{% block body %}


<div class="container mt-6">
    <div class="row">
        <div class="col-md-6">
            <form method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                <input type="hidden" name="bookID" value={{book.bookID}}>
                <div class="form-group">
                    <label for="bookname">Book Name</label>
                    <input type="text" class="form-control" name="bookname" id="bookname" value="{{book.bookname}}">
                </div>
                <div class="form-group">
                    <label for="bookPrice">Book Price</label>
                    <input type="text" class="form-control" id="bookPrice" name="bookPrice" value="{{book.bookPrice}}">
                </div>
                <div class="form-group">
                    <label for="bookState">Book Price</label>
                    <select class="form-control" name="bookState" id="bookState" disabled>
                        {% if bookSelected %}
                        <option value="available" selected >Availabel</option>
                        <option value="notavailable">Not available</option>
                        {% else %}
                        <option value="available">Availabel</option>
                        <option value="notavailable" selected >Not available</option>
                        {% endif %}
                    </select>
                </div>
                <button type="submit" class="btn btn-primary">Submit</button>
            </form>
        </div>
    </div>
    {% if flag %}
    <div class="row">
        <div class="col-md-4">
           <p>Book added succesfully</p> 
        </div>
    </div>
    {% endif %}
</div>

{% endblock %}

LibraryManagementSystem/LMSsite/LMSapp/templates/LMSapp/updatemember.html
{% extends 'LMSapp/base.html' %}
{% block body %}
<div class="container mt-6">
    <div class="row">
        <div class="col-md-6">
            <form method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="form-group">
                    <label for="studentName">Student Name</label>
                    <input type="text" class="form-control" name="studentName" id="studentName" value="{{student.studentName}}">
                </div>
                <div class="form-group">
                    <label for="studentEmailID">Student emailID</label>
                    <input type="email" class="form-control" id="studentEmailID" name="studentEmailID" value="{{student.studentEmailID}}">
                </div>
                <button type="submit" class="btn btn-primary">Update</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

LibraryManagementSystem/LMSsite/LMSapp/templates/LMSapp/viewbooks.html
{% extends 'LMSapp/base.html' %}
{% block body %}

<div class="container" style="margin-top: 8rem;">
    <div class="row">
        {% for book in data %}
        <div class="col-md-4">
            <div class="card mt-5" style="width: 18rem;">
                <div class="card-body">
                    <h3 class="card-title">{{book.bookname}}</h3>
                    <h6 class="card-subtitle mb-2 text-muted">{{book.bookPrice}}</h6>
                    <p class="card-text">{{book.bookState}}</p>
                    <a href="{% url 'LMSapp:updatebook' book.bookID %}" class="card-link">Update</a>
                    <a href="{% url 'LMSapp:deletebook' book.bookID %}" class="card-link">Delete</a>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
    {% if flag %}
    <div class="row">
        <div class="col-md-4">
            <p>
                {{msg}}
            </p>
        </div>
    </div>
    {% endif %}
</div>

{% endblock %}

LibraryManagementSystem/LMSsite/LMSapp/templates/LMSapp/viewmembers.html
{% extends 'LMSapp/base.html' %}
{% block body %}

<div class="container" style="margin-top: 8rem;">
    <div class="row">
        {% for student in data %}
        <div class="col-md-4">
            <div class="card mt-5" style="width: 18rem;">
                <div class="card-body">
                    <h3 class="card-title">{{student.studentName}}</h3>
                    <h6 class="card-subtitle mb-2 text-muted">{{student.studentEmailID}}</h6>
                    <a href="{% url 'LMSapp:updatemember' student.studentID %}" class="card-link">Update</a>
                    <a href="{% url 'LMSapp:deletemember' student.studentID %}" class="card-link">Delete</a>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
    {% if flag %}
    <div class="row">
        <div class="col-md-4">
            <p>
                {{msg}}
            </p>
        </div>
    </div>
    {% endif %}
</div>


{% endblock %}