Demo/MySite/MyApp/urls.py
from django.contrib import admin
from django.urls import path
from MyApp import views

app_name = 'MyApp'
urlpatterns = [
    path('', views.index, name='index'),
    path("products/", views.products, name='products'),

    # to pass variable to url, write static paart then <type of varibale(int, string) : name of variable> 
    path("products/book/<int:book_id>", views.details, name='details'),
    path('add/', views.add_book, name="addBook"),
    path("update/<int:book_id>/", views.update, name="update"),
    path("delete/<int:book_id>/", views.delete, name="delete"),
]

Demo/MySite/MySite/urls.py
from django.contrib import admin
from django.urls import path, include
from MyApp import views
from . import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('MyApp.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Demo/MySite/MyApp/models.py
from django.db import models


# Create your models here.
# it is used to create DB rekated stuff

class Book(models.Model):

    def __str__(self):
        return self.name + " : " + self.genre + " : " + str(self.price)

    name = models.CharField(max_length=100)
    genre = models.CharField(max_length=100)
    price = models.IntegerField()
    book_image = models.ImageField(default='default.jpg', upload_to='book_images/')

Demo/MySite/MyApp/forms.py
from django import forms
from .models import Book

class BookForm(forms.ModelForm):
    class Meta:
        model = Book
        fields = ['name', 'genre', 'price', 'book_image']

Demo/MySite/MyApp/views.py
from django.shortcuts import redirect, render
from django.http import HttpResponse
from .models import Book
from .forms import BookForm


# Create your views here.

# views in django are nothing but an functions that accepts requests
# apply view with particular url pattern
def index(request):
    books = Book.objects.all() # this is an context
    print(books)
    context = {
        'books': books
    }
    return render(request, 'MyApp/index.html', context)


def products(request):
    books = Book.objects.all() # this is an context
    print(books)
    context = {
        'books': books
    }
    return render(request, 'MyApp/index.html', context)




def details(request, book_id):

    books_details = Book.objects.get(id=book_id)
    context = {
        "books_details": books_details
    }
    return render(request, 'MyApp/details.html', context)



def add_book(request):

    if request.method == "POST":
        name = request.POST.get('name',)
        genre = request.POST.get('genre',)
        price = request.POST.get('price',)
        book_image = request.FILES['book_image']

        book = Book(name=name, genre=genre, price=price, book_image=book_image)
        book.save()

    return render(request, 'MyApp/add_book.html')



def update(request,book_id):
    book = Book.objects.get(id=book_id)
    # creating form object and passing request.POST or None, FILES if any and instance of book object which is to be updated
    form = BookForm(request.POST or None, request.FILES, instance=book)
    if form.is_valid():
        form.save()
        return redirect('/products/')    
    return render(request, 'MyApp/update.html', {'form': form, 'book': book})


def delete(request,book_id):

    if request.method == "POST":

        book = Book.objects.get(id=book_id)
        result = book.delete()
        if result[0] == 1:
            return redirect('/products/')

    return render(request, "Myapp/delete.html")

Demo/MySite/MyApp/templates/MyApp/add_book.html
{% extends 'MyApp/base.html' %}


{% block body%}

<br>
<form method="POST" enctype="multipart/form-data"> 
    {% csrf_token %}
    <!-- name filed shoul be set to varibales names in models -->
    Enter Book name
    <input type="text" name="name" id="name" placeholder="enter name of the book"></input>
    <br><br>
    Enter Genre 
    <input type="text" name="genre" id="genre", placeholder="Enter genre">
   <br><br>
    Enter Price 
    <input type="text" name="price" id="price" placeholder="Enter price">
    <br><br>
    Add cover
    <input type="file", name="book_image", id="book_image">
    <br><br>
    <input type="submit" name="">
    <a class="btn btn-warning" href="{% url 'MyApp:products' %}"> Back </a>
</form>
{% endblock %}

Demo/MySite/MyApp/templates/MyApp/base.html
{% load static %}
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]>      <html class="no-js"> <!--<![endif]-->
<html>
    <head>        
        <title></title>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
        <link rel="preconnect" href="https://fonts.gstatic.com">
        <link href="https://fonts.googleapis.com/css2?family=Lora:ital,wght@0,400;0,500;0,600;1,600&display=swap" rel="stylesheet">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
        <link rel="stylesheet" href="{% static 'MyApp/style.css' %}">
    </head>
    <body>
    <nav class="navbar navbar-dark bg-dark">
        <a class="navbar-brand" href="{% url 'MyApp:products' %}">
            Online Book Store
        </a>
    </nav>


    <!-- Here we place/embed content iof different html files-->
    {% block body %}

    {% endblock %}
</html>

Demo/MySite/MyApp/templates/MyApp/delete.html
{% extends 'MyApp/base.html' %}

{% block body %}
<br>
<form method="POST">
{% csrf_token %}

Are you sure you want to delete this book?
<input type="submit">
<a class="btn btn-warning" href="{% url 'MyApp:products' %}"> Cancel </a>
</form>
{% endblock %}

Demo/MySite/MyApp/templates/MyApp/details.html
{% extends 'MyApp/base.html' %}

        
    {% block body%}
    <br> <br>
        <ul>
           <li>
                <div height=200px width=100px>
                <img width=100% class="book_image" src="{{books_details.book_image.url}}"> </img>
                </div>
            </li>
            <br>           
            <li> Name : {{books_details.name}} </li>
            <li> Genre : {{books_details.genre}} </li>
            <li> Price : {{books_details.price}} </li>
            <br>
            <li><a class="btn btn-warning" href="{% url 'MyApp:update' books_details.id %}"> Update This Book </a></li>
            <br>
            <li><a class="btn btn-warning" href="{% url 'MyApp:delete' books_details.id %}"> Delete This Book </a></li>
        </ul>
    {% endblock %}

Demo/MySite/MyApp/templates/MyApp/index.html
{% extends 'MyApp/base.html' %}


{% block body %}
    {% for book in books %}
        <a href="{% url 'MyApp:details' book.id %}"> {{book.name}} </a>
        <br>
    {% endfor %}
<br><br>
<button type="button"><a href="{% url 'MyApp:addBook' %}"> Add Book </a>
{% endblock %}

Demo/MySite/MyApp/templates/MyApp/update.html
{% extends 'MyApp/base.html' %}
{% block body%}

    <form method="POST" enctype="multipart/form-data">

        {% csrf_token %}

        {{ form.as_p }}
        <input type="submit" name="Submit">

    </form>

{% endblock %}