BlogDemo/MyBlog/MyBlog/urls.py
from django.contrib import admin
from django.urls import path, include
from MyBlogApp import views
from . import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('MyBlogApp.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

BlogDemo/MyBlog/MyBlogApp/urls.py
from django.contrib import admin
from django.urls import path
from MyBlogApp import views


app_name = 'MyBlogApp'
urlpatterns = [
    path('', views.index, name='index'),
    path('register/', views.register, name='register' ),
    path('success/', views.success, name='success'),
    path('loginFresh/', views.login_fresh, name='login_fresh'),
    path('login/', views.login, name='login'),
    path('warning/', views.warning, name='warning'),
    path('loginsuc/', views.loginSuccess, name='login_success'),
    path('profile/', views.profile, name='profile'),
    path('logout/', views.logout, name='logout'),
    path('updateprofile/', views.update, name='updateprofile'),
    path('addblog/', views.addBlog, name='addblog'),
    path('viewblog/blog/<int:blog_id>', views.viewBlog, name='viewblog'),
]

BlogDemo/MyBlog/MyBlogApp/models.py
from django.db import models
import datetime

# Create your models here.

class UserData(models.Model):

    def __str__(self):

        return self.name

    name = models.CharField(max_length=100)
    email_id = models.CharField(max_length=100)
    password = models.CharField(max_length=100)
    phn_number = models.CharField(max_length=100)
    profileImage = models.ImageField(default='default..png', upload_to='profile_images/')

class Blogs(models.Model):

    def __str__(self):

        return self.title
    
    title = models.CharField(max_length=100)
    author = models.ForeignKey(UserData, on_delete=models.CASCADE)
    createdOn = models.DateField(default=datetime.datetime.now())
    coverImage = models.ImageField(default='blogdefault.jpg', upload_to='blog_images/')
    content = models.TextField()

BlogDemo/MyBlog/MyBlogApp/views.py
from django.shortcuts import render, redirect
from .models import UserData, Blogs
from MyBlog  import settings

# Create your views here.


def index(request):

    allBlogs = Blogs.objects.all()

    context = {
        "blogs" : allBlogs
    }

    return render(request, 'MyBlogApp/index.html', context)



def success(request):
    context = {
        "msg" : "msg"
    }
    return render(request, 'MyBlogApp/success.html', context)



def register(request):
    if request.method == 'POST':
        name = request.POST.get('name',)
        email_id = request.POST.get('email_id',)
        password = request.POST.get('password',)
        phn_number = request.POST.get('phn_number',)
        try:
            profileImage = request.FILES['profileImage']
        except:
            profileImage = "default.png"

        userData = UserData(name=name, email_id=email_id, password=password, phn_number=phn_number, profileImage=profileImage)
        userData.save()
        context = {
            "msg" : "registeration"
        }
        return render(request, 'MyBlogApp/success.html', context)

    return render(request, 'MyBlogApp/Register.html')




def login_fresh(request):
    return render(request, 'MyBlogApp/login.html')



def login(request):
    if request.method == 'POST':
        user_name = request.POST.get('email_id')
        password = request.POST.get('password')
        if user_name == '' and password == '':
            return render(request, 'MyBlogApp/warning.html')        
        else:
            userData = UserData.objects.get(email_id=user_name)
            if userData.email_id == user_name and userData.password == password:
                request.session['user'] = user_name
                return redirect('/loginsuc/')
            else:
                return render(request, 'MyBlogApp/warning.html')

    return render(request, 'MyBlogApp/login.html')



def warning(request):
    return render(request, 'MyBlogApp/warning.html')



def loginSuccess(request):
    if 'user' in request.session:
        current_user = UserData.objects.get(email_id=request.session['user'])
        blogs = Blogs.objects.all()
        blogs = [blog for blog in blogs if blog.author.email_id == current_user.email_id]
        context = {
            'user' : current_user,
            'blogs': blogs
        }
        return render(request, 'MyBlogApp/loginSuc.html', context)
    else:
        return redirect('/login_fresh/')  



def profile(request):
    if 'user' in request.session:
        current_user = UserData.objects.get(email_id=request.session['user'])
        
        context = {
            'user' : current_user
        }
        return render(request, 'MyBlogApp/profile.html', context)
    else:
        return redirect('/')


def logout(request):
    try:
        del request.session['user']
        return redirect('/')
    except:
        return redirect('/')



def update(request):
    if request.method == "POST":
        if 'user' in request.session:
            #old values
            prev_info = UserData.objects.get(email_id=request.session['user'])
            prev_name = prev_info.name
            prev_email_id = prev_info.email_id
            prev_phn_number = prev_info.phn_number
            prev_profileImage = prev_info.profileImage

            print(prev_profileImage )

            # updated values
            name = request.POST.get('name',)
            email_id = request.POST.get('email_id',)
            phn_number = request.POST.get('phn_number',)

            try:
                profileImage = request.FILES['profileImage']
                prev_info.profileImage = profileImage
                print(profileImage)
            except:
                prev_info.profileImage = prev_profileImage


            if name == '':                
                prev_info.name = prev_name
            else:
                prev_info.name = name
            if email_id == '':
                prev_info.email_id = prev_email_id
            else:
                prev_info.email_id = email_id
            if phn_number == '':
                prev_info.phn_number = prev_phn_number
            else:
                prev_info.phn_number = phn_number           
            prev_info.save()
            return redirect('/profile/')
        
        else:
            return redirect('/')

    if 'user' in request.session:
        #old values
        prev_info = UserData.objects.get(email_id=request.session['user'])
        context = {
            'user' : prev_info
        }
        return render(request, 'MyBlogApp/updateprofile.html', context)
    else:
        return redirect('/')




def addBlog(request):
    if request.method == 'POST':
        if 'user' in request.session:
            user = UserData.objects.get(email_id=request.session['user'])
            title = request.POST.get('title',)
            author = user
            content = request.POST.get('content',)
            try:
                coverImage = request.FILES['coverImage']
            except:
                coverImage =  "blogdefault.jpg"
                print(coverImage)

            if title == '' or content == '':
                return redirect('/loginsuc/')
            else:
                blog = Blogs(title=title,author=author,content=content,coverImage=coverImage )
                blog.save()
                return redirect('/loginsuc/')    
    
    if 'user' in request.session:
        #old values
        prev_info = UserData.objects.get(email_id=request.session['user'])
        context = {
            'user' : prev_info
        }
        return render(request, 'MyBlogApp/addBlog.html', context)
    else:
        return redirect('/')


def viewBlog(request, blog_id):

    if 'user' in request.session:        
        user = UserData.objects.get(email_id= request.session['user'])
        blog = Blogs.objects.get(id = blog_id)
        context = {
            'user': user,
            "blog" : blog
        }
        return render(request, 'MyBlogApp/viewuserblog.html', context)

    
    else:
        blog = Blogs.objects.get(id = blog_id)
        context = {
            "blog" : blog
        }
        return render(request, 'MyBlogApp/viewblog.html', context)





    

    
    

BlogDemo/MyBlog/MyBlogApp/templates/MyBlogApp/addBlog.html
{% extends 'MyBlogApp/loginSuc.html' %}

{% block body %}

<div class="register_form">
    <form method='POST' enctype='multipart/form-data'>
        {% csrf_token %}
        <div class="register_form_heading">
            <h4 class="register_heading"> Add your Blog </h4>
        </div>
        <div class="register_input_box">
            <div class="register_input">
                <label for="title" class="input_label">Title Of Blog</label>
                <input type="text" class="input" name="title" id="title" placeholder="Enter title" requeired>
            </div>

            <div class="register_input">
                <label for="content" class="input_label">Content</label>
                <input type="text" class="input blog_content" name="content" id="content"
                    placeholder="Enter blog content here" requeired>
            </div>

            <div class="register_input">
                <label for="coverImage" class="input_label">Upload cover image</label>
                <input type="file" class="input" name="coverImage" id="coverImage">
            </div>

            <div class="submit">
                <input type="submit" class="btn" name="">
            </div>

        </div>
    </form>
</div>

{% endblock %}

BlogDemo/MyBlog/MyBlogApp/templates/MyBlogApp/base.html
{% load static %}

<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]>      <html class="no-js"> <!--<![endif]-->
<html>

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title></title>
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Averia+Serif+Libre:wght@300;400;700&display=swap"
        rel="stylesheet">
    <link rel="stylesheet" href="{% static 'MyBlogApp/style.css' %}">
</head>

<body>
    <div class="nav_container">
        <div class="nav_heading_container">
            <h2 class="nav_heading"> <a class="nav_home_link" href="{% url 'MyBlogApp:index' %}"> My Blog </a></h2>
        </div>
        <div class="nav_widget">
            <div class="nav_login_container">
                <a class="nav_login" href="{% url 'MyBlogApp:login_fresh' %}"> Login </a>
            </div>
            <div class="nav_register_container">
                <a class="nav_register" href="{% url 'MyBlogApp:register' %}">Register</a>
            </div>
        </div>
    </div>
</body>

{% block body%}

{% endblock %}


<footer class="footer">

    <div class="copyright">

        <h3 class="footer_name"> My Blog </h3>
        <h5 class="copyright_mark"> All rights reserved @ 2021 </h5>

    </div>

</footer>

</html>

BlogDemo/MyBlog/MyBlogApp/templates/MyBlogApp/index.html
{% extends 'MyBlogApp/base.html' %}
{% load static %}
{% block body %}
<div class="Blog_containers">
    <div class="main_blogs">
        {%for blog in blogs%}
        <div class="blog_box">
            <div class="blog_title_box">
                <h3 class="title"> {{blog.title}} </h3>
            </div>
            <div class="blog_meta_box">
                <div class="blog_author_box">
                    <p class="blog_author"> {{blog.author.name}}</p>
                </div>
                <div class="blog_date_box">
                    <p class="blog_date"> | {{blog.createdOn}}</p>
                </div>
            </div>
            <div class="blog_content_box">
                <p class="blog_content"> {{ blog.content | slice:":200" }}....</p>
            </div>

            <div class="blog_read_button">
                <a href="{% url 'MyBlogApp:viewblog' blog.id %}" class="btn blog_btn">Read more</a>
                </a>
            </div>
        </div>
        {% endfor %}
    </div>
    <div class="blog_creator_info">
        <div class="creator_box">
            <div class="creator_pic">
                <img src="{% static 'img/AbhiMain.jpg' %}" class="creator">
            </div>
            <div class="creator_name">
                <h3 class="name">
                    Abhijit Morye
                </h3>
            </div>
            <div class="creator_info_box">
                <p class="creator_info">

                    I am an IT professional with 4 years of experience as Performance engineer in performance testing
                    and Performance engineering field.

                    Currently I am learning development especially full stack development where i am learning Python web
                    framework, HTML, and
                    CSS, Javascript and many more languages to become omniscient in IT field.

                    I am going to become Machine Learning Engineer as Google.

                </p>
            </div>
        </div>
    </div>
</div>
{% endblock %}

BlogDemo/MyBlog/MyBlogApp/templates/MyBlogApp/login.html
<!DOCTYPE html>
{% load static %}
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]>      <html class="no-js"> <!--<![endif]-->
<html>

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title></title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static 'MyBlogApp/style.css'%}">
</head>

<body>
    <div class="nav_container">
        <div class="nav_heading_container">
            <h2 class="nav_heading"> <a class="nav_home_link" href="{% url 'MyBlogApp:index' %}"> My Blog </a></h2>
        </div>
        {% comment %} <div class="nav_widget">
            <div class="nav_login_container">
                <a class="nav_login" href="#"> Login </a>
            </div>
            <div class="nav_register_container">
                <a class="nav_register" href="{% url 'MyBlogApp:register' %}">Register</a>
            </div>
        </div> {% endcomment %}
    </div>

    <div class="register_form">
        <form method='POST' action="{% url 'MyBlogApp:login' %}" enctype='multipart/form'>
            {% csrf_token %}
            <div class="register_form_heading">
                <h4 class="register_heading"> Login </h4>
            </div>
            <div class="register_input_box">

                <div class="register_input">
                    <label for="email_id" class="input_label">Email ID:</label>
                    <input type="text" class="input" name="email_id" id="email_id" placeholder="Enter you email ID"
                        requeired>
                </div>

                <div class="register_input">
                    <label for="password" class="input_label">Enter password</label>
                    <input type="password" class="input" name="password" id="password" placeholder="Enter you password"
                        requeired>
                </div>

                <div class="submit">
                    <button type="submit" class="btn" name="">Login</button>
                </div>

            </div>
        </form>
    </div>

    <footer class="footer">

        <div class="copyright">

            <h3 class="name"> My Blog </h3>
            <h5 class="copyright_mark"> All rights reserved @ 2021 </h5>

        </div>

    </footer>
</body>

</html>

BlogDemo/MyBlog/MyBlogApp/templates/MyBlogApp/loginSuc.html
{% load static %}

<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]>      <html class="no-js"> <!--<![endif]-->
<html>

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title></title>
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Averia+Serif+Libre:wght@300;400;700&display=swap"
        rel="stylesheet">
    <link rel="stylesheet" href="{% static 'MyBlogApp/style.css' %}">
</head>

<body>
    <div class="nav_container">
        <div class="nav_heading_container">
            <h2 class="nav_heading"> <a class="nav_home_link" href="{% url 'MyBlogApp:login_success' %}"> My Blog </a>
            </h2>
        </div>
        <div class="user_widget">
            <div class="user_profile">
                <h4 class="user_name"> Welcome {{user.name}} ! </h4>
            </div>
            <div class="user_pic">
                <a class="user" href="{% url 'MyBlogApp:profile' %}"> <img src="{{user.profileImage.url}}"
                        class="user_img"></img> </a>
            </div>
        </div>
    </div>



</body>

{% block body%}
<div class="Blog_containers">
    <div class="main_blogs">
        {%for blog in blogs%}
        <div class="blog_box">
            <div class="blog_title_box">
                <h3 class="title"> {{blog.title}} </h3>
            </div>
            <div class="blog_meta_box">
                <div class="blog_author_box">
                    <p class="blog_author"> {{blog.author.name}}</p>
                </div>
                <div class="blog_date_box">
                    <p class="blog_date"> | {{blog.createdOn}}</p>
                </div>
            </div>
            <div class="blog_content_box">
                <p class="blog_content"> {{ blog.content | slice:":200" }}....</p>
            </div>

            <div class="blog_read_button">
                <a href="{% url 'MyBlogApp:viewblog' blog.id %}" class="btn blog_btn">Read more</a>
                </a>
            </div>
        </div>
        {% endfor %}
    </div>
    <div class="Blog_widgets">
        <a class="btn btn-blog-widget" href="{% url 'MyBlogApp:addblog' %}">Add Blog</a>
    </div>
</div>
{% endblock %}

<footer class="footer">

    <div class="copyright">

        <h3 class="footer_name"> My Blog </h3>
        <h5 class="copyright_mark"> All rights reserved @ 2021 </h5>

    </div>

</footer>

</html>

BlogDemo/MyBlog/MyBlogApp/templates/MyBlogApp/profile.html
{% extends 'MyBlogApp/loginSuc.html' %}

{% block body %}

<div class="main_container">
    <div class="profile_container">
        <img class="profile_img" src="{{user.profileImage.url}}"></img>
    </div>
    <div class="profile_info_container">
        <div class="profile_info">
            <h4 class="info"> <span style: "color: #f29191"> Name </span> : {{user.name}} </h4>
        </div>

        <div class="profile_info">
            <h4 class="info"> <span style: "color: #f29191"> Email ID </span> : {{user.email_id}} </h4>
        </div>

        <div class="profile_info">
            <h4 class="info"> <span style: "color: #f29191"> Phone </span> : {{user.phn_number}} </h4>
        </div>
    </div>

    <div class="profile_widgets">
        <div class="widget">
            <a href="{% url 'MyBlogApp:updateprofile' %}" class="btn btn_widget"> Update Profile </a>
        </div>
        <div class="widget">
            <a href="{% url 'MyBlogApp:logout' %}" class="btn btn_widget"> Logout </a>
        </div>
    </div>
</div>

{% endblock %}

BlogDemo/MyBlog/MyBlogApp/templates/MyBlogApp/register.html
<!DOCTYPE html>
{% load static %}
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]>      <html class="no-js"> <!--<![endif]-->
<html>

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title></title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static 'MyBlogApp/style.css'%}">
</head>

<body>
    <div class="nav_container">
        <div class="nav_heading_container">
            <h2 class="nav_heading"> <a class="nav_home_link" href="{% url 'MyBlogApp:index' %}"> My Blog </a></h2>
        </div>
        {% comment %} <div class="nav_widget">
            <div class="nav_login_container">
                <a class="nav_login" href="#"> Login </a>
            </div>
            <div class="nav_register_container">
                <a class="nav_register" href="{% url 'MyBlogApp:register' %}">Register</a>
            </div>
        </div> {% endcomment %}
    </div>

    <div class="register_form">
        <form method='POST' enctype='multipart/form-data'>
            {% csrf_token %}
            <div class="register_form_heading">
                <h4 class="register_heading"> Registeration </h4>
            </div>
            <div class="register_input_box">
                <div class="register_input">
                    <label for="fname" class="input_label">First name:</label>
                    <input type="text" class="input" name="name" id="name" placeholder="Enter you name" requeired>
                </div>

                <div class="register_input">
                    <label for="email_id" class="input_label">Email ID:</label>
                    <input type="text" class="input" name="email_id" id="email_id" placeholder="Enter you email ID"
                        requeired>
                </div>

                <div class="register_input">
                    <label for="password" class="input_label">Enter password</label>
                    <input type="password" class="input" name="password" id="password" placeholder="Enter you password"
                        requeired>
                </div>

                <div class="register_input">
                    <label for="phn_number" class="input_label">Enter phone</label>
                    <input type="text" class="input" name="phn_number" id="phn_number" placeholder="Enter you phone"
                        requeired>
                </div>

                <div class="register_input">
                    <label for="profileImage" class="input_label">Upload profile Image</label>
                    <input type="file" class="input" name="profileImage" id="profileImage">
                </div>

                <div class="submit">
                    <input type="submit" class="btn" name="">
                </div>

            </div>
        </form>
    </div>

    <footer class="footer">

        <div class="copyright">

            <h3 class="name"> My Blog </h3>
            <h5 class="copyright_mark"> All rights reserved @ 2021 </h5>

        </div>

    </footer>
</body>

</html>

BlogDemo/MyBlog/MyBlogApp/templates/MyBlogApp/success.html
<!DOCTYPE html>
{% load static %}
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]>      <html class="no-js"> <!--<![endif]-->
<html>

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title></title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static 'MyBlogApp/style.css'%}">
</head>

<body>
    <div class="nav_container">
        <div class="nav_heading_container">
            <h2 class="nav_heading"> <a class="nav_home_link" href="{% url 'MyBlogApp:index' %}"> My Blog </a></h2>
        </div>
        {% comment %} <div class="nav_widget">
            <div class="nav_login_container">
                <a class="nav_login" href="#"> Login </a>
            </div>
            <div class="nav_register_container">
                <a class="nav_register" href="{% url 'MyBlogApp:register' %}">Register</a>
            </div>
        </div> {% endcomment %}
    </div>

    <div class="register_form">
        <h4 class=""> {{msg}} successfull ! </h4>
    </div>

    <footer class="footer">

        <div class="copyright">

            <h3 class="name"> My Blog </h3>
            <h5 class="copyright_mark"> All rights reserved @ 2021 </h5>

        </div>

    </footer>
</body>

</html>

BlogDemo/MyBlog/MyBlogApp/templates/MyBlogApp/updateprofile.html
{% extends 'MyBlogApp/loginSuc.html' %}

{%block body %}

<div class="register_form">
    <form method='POST' enctype='multipart/form-data'>
        {% csrf_token %}
        <div class="register_form_heading">
            <h4 class="register_heading"> Update Profile </h4>
        </div>
        <div class="register_input_box">
            <div class="register_input">
                <label for="fname" class="input_label">First name:</label>
                <input type="text" class="input" name="name" id="name" value="{{user.name}}" requeired>
            </div>

            <div class="register_input">
                <label for="email_id" class="input_label">Email ID:</label>
                <input type="text" class="input" name="email_id" id="email_id" value="{{user.email_id}}"
                    requeired>
            </div>

            <div class="register_input">
                <label for="phn_number" class="input_label">Enter phone</label>
                <input type="text" class="input" name="phn_number" id="phn_number" value="{{user.phn_number}}"
                    requeired>
            </div>

            <div class="register_input">
                <label for="profileImage" class="input_label">Upload profile Image</label>
                <input type="file" class="input" name="profileImage" id="profileImage" value="{{user.profileImage.url}}">
            </div>

            <div class="submit">
                <input type="submit" class="btn" name="">
                <a class ="btn back-btn" href="{% url 'MyBlogApp:profile' %}"> Back </a>
            </div>

        </div>
    </form>
</div>

{% endblock %}

BlogDemo/MyBlog/MyBlogApp/templates/MyBlogApp/viewblog.html
{% extends 'MyBlogApp/base.html' %}

{% block body %}

<div class="main_view_blog_container">

    <div class="blog_view_main_box">

        <div class="blog_view_cover_image">
            <img src="{{blog.coverImage.url}}" class="blog_view_cover_image">
        </div>

        <div class="blog_view_data">
            <div class="blog_view_title">
                <h2 class="title title_mod"> {{blog.title}} </h2>
            </div>

            <div class="blog_view_meta_data">
                <div class="blog_view_autor_box">
                    <p class="blog_author"> {{blog.author}} </p>
                </div>

                <div class="blog_view_date_box">
                    <p class="blog_date"> | {{blog.createdOn}} </p>
                </div>
            </div>

            <div class="blog_view_content_box">
                <p class="blog_view_content">
                    {{blog.content}}
                </p>
            </div>
        </div>

    </div>
</div>

{% endblock %}

BlogDemo/MyBlog/MyBlogApp/templates/MyBlogApp/viewuserblog.html
{% extends 'MyBlogApp/loginSuc.html' %}

{% block body %}

<div class="main_view_blog_container">

    <div class="blog_view_main_box">

        <div class="blog_view_cover_image">
            <img src="{{blog.coverImage.url}}" class="blog_view_cover_image">
        </div>

        <div class="blog_view_data">
            <div class="blog_view_title">
                <h2 class="title title_mod"> {{blog.title}} </h2>
            </div>

            <div class="blog_view_meta_data">
                <div class="blog_view_autor_box">
                    <p class="blog_author"> {{blog.author}} </p>
                </div>

                <div class="blog_view_date_box">
                    <p class="blog_date"> | {{blog.createdOn}} </p>
                </div>
            </div>

            <div class="blog_view_content_box">
                <p class="blog_view_content">
                    {{blog.content}}
                </p>
            </div>
        </div>

    </div>
</div>

{% endblock %}

BlogDemo/MyBlog/MyBlogApp/templates/MyBlogApp/warning.html
{% extends 'MyBlogApp/base.html' %}

{% block body %}

        <div class="register_form">
            <h4 class="warning"> Failed login attempt. <a href="{% url 'MyBlogApp:login_fresh' %}" class="login_again">Try again </h4>
        </div>

{%endblock %}