ToDoTasks/ToDoTaskSite/ToDoTaskApp/urls.py
from django.urls import path
from ToDoTaskApp import views


app_name = 'ToDoTaskApp'
urlpatterns = [
    path('', views.index, name='index'),
    path('addtask/', views.addTask, name='addTask'),
    path('viewTasks/', views.viewTasks, name='viewTasks'),
    path('viewTasks/<int:task_id>/', views.viewSingleTask, name='viewSingleTask'),
    path('deletetasks/<int:task_id>/', views.deleteSingleTasks, name='deleteSingleTasks'),
    path('updatetask/<int:task_id>/', views.updateTask, name='updateTask'),
]

ToDoTasks/ToDoTaskSite/ToDoTaskSite/urls.py
from django.contrib import admin
from django.urls import path, include
from ToDoTaskApp import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('ToDoTaskApp.urls')),
]

ToDoTasks/ToDoTaskSite/ToDoTaskApp/models.py
from django.db import models

# Create your models here.

class Tasks(models.Model):

    def __str__(self):

        return self.taskTitle
    
    taskTitle = models.CharField(max_length=100)

    taskDesc = models.CharField(max_length=500)

    taskAuthor = models.CharField(max_length=100)

ToDoTasks/ToDoTaskSite/ToDoTaskApp/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .models import Tasks
from django.contrib import messages

# Create your views here.

def index(request):

    return render(request, 'ToDoTaskApp/index.html')



def addTask(request):

    if request.method == 'POST':
        taskTitle = request.POST.get('taskTitle',)
        taskDesc = request.POST.get('taskDesc',)
        taskAuthor = request.POST.get('taskAuthor',)

        task = Tasks(taskTitle=taskTitle, taskDesc=taskDesc, taskAuthor=taskAuthor)
        task.save()
        # messages.success(request, 'task addedd successfully!')

        return redirect('/viewTasks/')

    return render(request, 'ToDoTaskApp/addTask.html')




def viewTasks(request):
    tasks = Tasks.objects.all()

    context = {

        "tasks" : tasks
    }

    return render(request, 'ToDoTaskApp/viewTasks.html', context)


def viewSingleTask(request, task_id):

    task = Tasks.objects.get(id=task_id)

    context = {
        'task': task
    }

    return render(request, 'ToDoTaskApp/viewSingleTask.html', context)

def deleteSingleTasks(request, task_id):

    if request.method == 'POST':

        task = Tasks.objects.get(id=task_id)
        result = task.delete()
        if result[0] == 1:
            return redirect('/viewTasks/')

    context = {
        'id' : task_id
    }
        
    return render(request, 'ToDoTaskApp/deleteSingleTasks.html', context)


def updateTask(request, task_id):

    task = Tasks.objects.get(id=task_id)

    title = task.taskTitle
    desc = task.taskDesc
    author = task.taskAuthor

    if request.method == 'POST':

        if request.POST.get('taskTitle',) == '':
            task.taskTitle = title
        else:
            task.taskTitle = request.POST.get('taskTitle',)

        if request.POST.get('taskDesc',) == '':
            task.taskDesc = desc
        else:
            task.taskDesc = request.POST.get('taskDesc',)

        if request.POST.get('taskAuthor',) == '':
            task.taskAuthor = author
        else:
            task.taskAuthor = request.POST.get('taskAuthor',)
        
        task.save()

        # messages.success(request, 'task updated successfully!')

        return redirect('/viewTasks/{}/'.format(task.id))

    context = {
        'task' : task
    }

    return render(request, 'ToDoTaskApp/updateTask.html', context)

ToDoTasks/ToDoTaskSite/ToDoTaskApp/templates/ToDoTaskApp/addTask.html
{% extends 'ToDoTaskApp/base.html' %}

{% block body %}

<div class="container">
    <form method="POST" enctype="multipart/form-data" class="addform">

        {% csrf_token %}

        <div class="success_message">

            {% if messages %}
            <ul class="messages">
                {% for message in messages %}
                <h4> {{ message }} </h4>
                {% endfor %}
            </ul>
            {% endif %}

        </div>

        <div class="container_heading_box">
            <h3 class="container_heading"> Add Task </h3>
        </div>

        <div class="container_field">
            <label for="taskTitle" class="formlabel"> Task Title </label>
            <input type="text" , name="taskTitle" , id="taskTitle" , placeholder="Add Title" class="formfield">
        </div>

        <div class="container_field">
            <label for="taskDesc" class="formlabel"> Task Description </label>
            <input type="text" , name="taskDesc" , id="taskDesc" , placeholder="Add Description" class="formfield">
        </div>

        <div class="container_field">
            <label for="taskAuthor" class="formlabel"> Task Creator </label>
            <input type="text" , name="taskAuthor" , id="taskAuthor" , placeholder="Add creator" class="formfield">
        </div>

        <div class="submit_field">
            <input type="submit" name="" class="btn">
        </div>


    </form>
</div>

{% endblock %}

ToDoTasks/ToDoTaskSite/ToDoTaskApp/templates/ToDoTaskApp/base.html
<!DOCTYPE html>
{% load static %}
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]>      <html class="no-js"> <!--<![endif]-->
<html>

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title></title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link
        href="https://fonts.googleapis.com/css2?family=Fira+Sans:wght@300;400;500;600;700&family=Fredoka+One&display=swap"
        rel="stylesheet">
    <link rel="stylesheet" href="{% static 'ToDoTaskApp/style.css' %}">
</head>

<body>

    <a class="home_link" href="{% url 'ToDoTaskApp:index' %}">
        <div class="nav_container">

            <div class="logo_container">
                <img class="logo" src="{% static 'img/todologo.jpg' %}">
            </div>
            <h2 class="heading"> To Do App </h2>
        </div>
    </a>


    {% block body %}

    {% endblock %}



</body>

</html>

ToDoTasks/ToDoTaskSite/ToDoTaskApp/templates/ToDoTaskApp/deleteSingleTasks.html
{% extends 'ToDoTaskApp/base.html' %}

{% block body %}

<div class="confirmbox">
    <form method="POST" , enctype="multipart/form-data">
        {% csrf_token %}
        <label for="submit" class="confirmlabel"> Are you sure to remove the task? </label>
        <div class="cancelholder">
            <input type="submit" name="submit" value="remove task" class="btn_cancel">
            <a href="{% url 'ToDoTaskApp:viewSingleTask' id %}" class="btn_cancel btn_cancel_link"> Cancel </a>
        </div>
    </form>
</div>

{% endblock %}

ToDoTasks/ToDoTaskSite/ToDoTaskApp/templates/ToDoTaskApp/index.html
{% extends "ToDoTaskApp/base.html" %}

{% block body %}

<div class="widgets">
    <div class="widget">
        <a class="widget_link" href="{% url 'ToDoTaskApp:addTask' %}"> Add Task </a>
    </div>
    <div class="widget">
        <a class="widget_link" href="{% url 'ToDoTaskApp:viewTasks' %}"> View Task </a>
    </div>
</div>

{% endblock %}

ToDoTasks/ToDoTaskSite/ToDoTaskApp/templates/ToDoTaskApp/updateTask.html
{% extends 'ToDoTaskApp/base.html' %}

{% block body %}

<div class="container">
    <form method="POST" enctype="multipart/form-data" class="addform">

        {% csrf_token %}

        {% comment %} <div class="success_message">

            {% if messages %}
            <ul class="messages">
                {% for message in messages %}
                <h4> {{ message }} </h4>
                {% endfor %}
            </ul>
            {% endif %}

        </div> {% endcomment %}

        <div class="container_heading_box">
            <h3 class="container_heading"> update Task - {{task.taskTitle}} </h3>
        </div>

        <div class="container_field">
            <label for="taskTitle" class="formlabel"> Task Title </label>
            <input type="text" , name="taskTitle" , id="taskTitle" , value="{{task.taskTitle}}" class="formfield">
        </div>

        <div class="container_field">
            <label for="taskDesc" class="formlabel"> Task Description </label>
            <input type="text" , name="taskDesc" , id="taskDesc" , value="{{task.taskDesc}}" class="formfield">
        </div>

        <div class="container_field">
            <label for="taskAuthor" class="formlabel"> Task Creator </label>
            <input type="text" , name="taskAuthor" , id="taskAuthor" , value="{{task.taskAuthor}}" class="formfield">
        </div>

        <div class="submit_field">
            <input type="submit" name="" class="btn" value="update">
        </div>


    </form>
</div>

{% endblock %}

ToDoTasks/ToDoTaskSite/ToDoTaskApp/templates/ToDoTaskApp/viewSingleTask.html
{% extends 'ToDoTaskApp/base.html' %}
{% block body %}

    <div class="taskviewccontainer">
    <div class="containerheading">
        <h4 class="tasksheading"> {{ task.taskTitle }} </h4>
    </div>

    <div class="containerbody">

        <div class="taskbody">
        <h4 class="tasklabel"> Task Name </h4>
        <h5 class="taskdata"> {{task.taskTitle}} </h5>
        </div>

        <div class="taskbody">
        <h4 class="tasklabel"> Task Description </h4>
        <h5 class="taskdata"> {{task.taskDesc}} </h5>
        </div>

        <div class="taskbody">
        <h4 class="tasklabel"> Task Creator </h4>
        <h5 class="taskdata"> {{task.taskAuthor}} </h5>
        </div>

    </div>

    <div class="buttoncontainer">
        <div class="buttoncontainer_1">
            <a href="{% url 'ToDoTaskApp:updateTask' task.id %}" class="btn btn_1"> Update </a>
        </div>
        <div class="buttoncontainer_1">
            <a href="{% url 'ToDoTaskApp:deleteSingleTasks' task.id %}" class="btn btn_1"> Remove Task </a>
        </div>
        <div class="buttoncontainer_1">
            <a href="#" class="btn btn_1"> Mark completed </a>
        </div>
    </div>
</div>

{% endblock %}

ToDoTasks/ToDoTaskSite/ToDoTaskApp/templates/ToDoTaskApp/viewTasks.html
{% extends 'ToDoTaskApp/base.html' %}

{% block body %}

<div class="taskviewccontainer">
    <div class="containerheading">
        <h4 class="tasksheading"> All Tasks </h4>
    </div>

    <div class="containerbody">

        {% for task in tasks %}

        <div class="taskbox">
            <input type="checkbox" class="taskcheckbox" name="check" id="{{ task.id }}">
            <label for="check[]" class="task">
                <a href="{% url 'ToDoTaskApp:viewSingleTask' task.id %}" class="taskLink"> {{task}} </a>
            </label>
        </div>

        {% endfor %}

    </div>

    <div class="buttoncontainer_1">
        <div class="buttoncontainer_1_1">
            <a href="{% url 'ToDoTaskApp:addTask' %}" class="btn btn_1"> Add Task </a>
        </div>
    </div>
</div>

{% endblock %}